var data = [
    {
        name: '海賊王',
        image: 'http://ecx.images-amazon.com/images/I/615UJbdsjvL._SX314_BO1,204,203,200_.jpg',
        author: '尾田 栄一郎',
        rates: '★★★★☆',
        lastepi: '第814話',
        feed: 'http://www.ishuhui.com/feed',
        from: '鼠繪漫畫網',
        fromURL: 'http://www.ishuhui.com/',
        des: '擁有財富、名聲、勢力、擁有世界上的一切的「海賊王」高路·D·羅傑在即將遭到處刑前說了一句話：「想要我的財寶嗎？想要的話可以全部給你。去找吧！我把所有的財寶都放在那裡！」後來世界上的人們將這個寶藏稱作「大秘寶」（ONE PIECE），許多人為了爭奪大秘寶「ONE PIECE」，而先後爭相出海成為海賊，因此造就了「大海賊時代」。主角蒙奇·D·路飛為了要實現與「紅髮」傑克斯的約定而出海，在遙遠的路途上找尋著志同道合的夥伴，一起進入「偉大的航道」，目標是得到「ONE PIECE」與成為「海賊王」。',
        lang: '中文',
        category: '熱血，長篇',
        lastdate: '2016年1月1日',
        site: 'about:blank',
        para1: 'onepiece',
        para2: '375357'
    },
    {
        name: '侵略！乌贼娘',
        image: 'http://images.dmzj.com/webpic/10/qinluewuzeiniang.jpg',
        author: '安部真弘',
        rates: '★★★★★',
        lastepi: '第233話',
        feed: 'http://manhua.dmzj.com/q/qinluewuzeiniang/rss.xml',
        from: '動漫之家漫畫網',
        fromURL: 'http://manhua.dmzj.com/',
        des: '血腥!暴力!恐怖! 來自海洋的侵略者!! 人類明天的命運將會如何 XD (其實是來自海洋自稱侵略者的激萌烏賊娘在海之屋不斷打工還債其間發生的各種故事……)一開始以為會變成某軍曹那種超展開子供向，結果……這裡的永遠都是夏天的海灘啊（嘆）。可愛的小姑娘是侵略者！？灼熱新連載，地上侵略喜劇！？',
        lang: '中文',
        category: '輕鬆，搞笑',
        lastdate: '2016年1月1日',
        site: 'about:blank',
        para1: '',
        para2: ''
    },
    {
        name: '名偵探柯南',
        image: 'http://images.dmzj.com/webpic/16/160131kenanfml.jpg',
        author: '青山剛昌',
        rates: '★★★★★',
        lastepi: '第233話',
        feed: 'http://manhua.dmzj.com/k/kenan/rss.xml',
        from: '動漫之家漫畫網',
        fromURL: 'http://manhua.dmzj.com/',
        des: '工藤新一，米花高中二年級學生，與小蘭是青梅竹馬，兩人感情很好。繼承了父親的超強推理能力，被譽為高中生名偵探。他喜歡看推理小說，最崇拜福爾摩斯，另外踢足球的水平也是一流。不幸被捲入黑衣組織的交易被灌下毒藥APTX4869，但是沒有死，只是變成了小孩，改名江戶川柯南（取自兩個偵探小說里的人名）。幸虧智力沒有衰退，還可以幫著毛利小五郎辦案以尋找黑衣組織的線索，而體力上的不足靠阿栗博士的發明來彌補。變小後就讀於米花小學1年紀B班，認識了步美、元太、光彥三人，並成立了少年偵探團。',
        lang: '中文',
        category: '推理，長篇',
        lastdate: '2016年1月1日',
        site: 'about:blank',
        para1: '',
        para2: ''
    },
    {
        name: '旋風管家',
        image: 'http://images.dmzj.com/webpic/19/1104xuanfengguanjiafml.jpg',
        author: '畑 健二郎',
        rates: '★★★★☆',
        lastepi: '第233話',
        feed: 'http://manhua.dmzj.com/x/xfgj/rss.xml',
        from: '動漫之家漫畫網',
        fromURL: 'http://manhua.dmzj.com/',
        des: '在三千院家擔任管家的小颯，展開了全新的生活。 除了保護遺產、被機器人攻擊、以及和黑道對抗，還要製造笑料… 各式各樣的難題接踵而來！！看來有錢人的生活果然不一樣的。',
        lang: '中文',
        category: '青春，搞笑',
        lastdate: '2016年1月1日',
        site: 'about:blank',
        para1: '',
        para2: ''
    },
    {
        name: '一拳超人',
        image: 'http://images.dmzj.com/webpic/1/yijinan20130105.jpg',
        author: '村田雄介',
        rates: '★★★★★',
        lastepi: '第233話',
        feed: 'http://manhua.dmzj.com/y/yiquanchaoren/rss.xml',
        from: '動漫之家漫畫網',
        fromURL: 'http://manhua.dmzj.com/',
        des: '主人公埼玉原本是一名整日奔波於求職的普通人。3年前的一天偶然遇到了要對淘氣少年下殺手的異變螃蟹人後，回憶起年少年時「想要成為英雄」的夢想，最終拼盡全力救下了淘氣少年。之後通過拼命鍛鍊，埼玉終於脫胎換骨獲得了最強的力量，但同時失去了頭髮成了光頭。在獨自做了一段時間英雄後，正式加入英雄協會，與眾多英雄一起開始了對抗各種怪人以及惡勢力的生活。',
        lang: '中文',
        category: '格鬥，搞笑',
        lastdate: '2016年1月1日',
        site: 'about:blank',
        para1: '',
        para2: ''
    }
];